name: stars
version: '2.7jrc3'
summary: STARS!
description: |
  Stars! is a turn-based strategy, science fiction 4X game. Stars! was developed
  by Jeff Johnson and Jeff McBride ("the Jeffs") for their own use, and
  initially released as shareware in 1995. A retail version was later produced
  for, and published by Empire Interactive, although the shareware version
  continued.

  It is no longer possible to purchase new Stars! serials, so under the
  principal of abandonware keys to unlock the game are included below.

  Keys:
    Choose one key from this list. In multiplayer mode, each player must have a
    unique serial number.
    
    Each key is eight (8) characters.

    E4TP99BW | E2BO659A | ECN101WP | EUTBD0AV | CJWLADUE | CXG6TIQX | CXLSIXTL
    CXR6TCXY | EPA8IRTP | GVZC2FZ5 | GX5RODYA | HAIDAAWS | HB5JYSQH | IFNKZG2R
    JU9VWLDF | SEOMBS8E | STDAG49L | SU0ODX1T | WBXU2GIX | WCES1YRZ | WV1EFJKF
    WV53517J | WX8Z8HLP | CJWLADUE | CXG6TIQX | CXLSIXTL | CXR6TCXY | EPA8IRTP
    GVZC2FZ5 | GX5RODYA | HAIDAAWS | HB5JYSQH | IFNKZG2R | JU9VWLDF | SEOMBS8E
    STDAG49L | SU0ODX1T | WBXU2GIX | WCES1YRZ | WV1EFJKF | WV53517J | WX8Z8HLP
icon: desktop/stars.png
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

layout:
  /usr/lib/x86_64-linux-gnu/dri:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/dri
  /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0
  /usr/lib/x86_64-linux-gnu/gstreamer1.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer1.0
  /usr/lib/x86_64-linux-gnu/gstreamer-1.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  /usr/lib/x86_64-linux-gnu/gtk-3.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/gtk-3.0
  /usr/lib/x86_64-linux-gnu/mesa:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/mesa
  /usr/lib/x86_64-linux-gnu/mesa-egl:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/mesa-egl
  /usr/lib/x86_64-linux-gnu/pulseaudio:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/pulseaudio
  /usr/lib/x86_64-linux-gnu/samba:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/samba

  /usr/lib/i386-linux-gnu/dri:
    bind: $SNAP/usr/lib/i386-linux-gnu/dri
  /usr/lib/i386-linux-gnu/gdk-pixbuf-2.0:
    bind: $SNAP/usr/lib/i386-linux-gnu/gdk-pixbuf-2.0
  /usr/lib/i386-linux-gnu/gstreamer1.0:
    bind: $SNAP/usr/lib/i386-linux-gnu/gstreamer1.0
  /usr/lib/i386-linux-gnu/gstreamer-1.0:
    bind: $SNAP/usr/lib/i386-linux-gnu/gstreamer-1.0
  /usr/lib/i386-linux-gnu/gtk-3.0:
    bind: $SNAP/usr/lib/i386-linux-gnu/gtk-3.0
  /usr/lib/i386-linux-gnu/mesa:
    bind: $SNAP/usr/lib/i386-linux-gnu/mesa
  /usr/lib/i386-linux-gnu/mesa-egl:
    bind: $SNAP/usr/lib/i386-linux-gnu/mesa-egl
  /usr/lib/i386-linux-gnu/pulseaudio:
    bind: $SNAP/usr/lib/i386-linux-gnu/pulseaudio
  /usr/lib/i386-linux-gnu/samba:
    bind: $SNAP/usr/lib/i386-linux-gnu/samba

apps:
  stars:
    command: bin/sommelier "$SNAP/Stars!-27jrc3.exe"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      DLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
      LC_ALL: "C.UTF-8"
      SNAP_TITLE: "Stars"
      SNAP_ICON: "$SNAP/usr/share/icons/stars.png"
      SNAP_SUPPORT_URL: "https://github.com/diddlesnaps/stars/issues"
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland
      - x11

parts:
  desktop:
    plugin: dump
    source: desktop
    organize:
      stars.png: usr/share/icons/stars.png
      stars.desktop: usr/share/applications/stars.desktop

  enable-i386:
    plugin: nil
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  wine:
    plugin: nil
    build-packages:
      - dpkg
      - wget
    override-build: |
      snapcraftctl build

      ARCH="$(dpkg --print-architecture)"
      WINE_REL="wine-stable"
      WINE_VER="4.0.1"

      # wget and dpkg extract the wine debs
      ## supporting binaries which are arch-specific but the same filenames in both architectures so we only install the native architecture
      DEB_URLS="https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-${ARCH}/${WINE_REL}_${WINE_VER}~bionic_${ARCH}.deb"

      ## wine loaders - this one is the native system architecture
      DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-${ARCH}/${WINE_REL}-${ARCH}_${WINE_VER}~bionic_${ARCH}.deb"

      if [ "$ARCH" = "amd64" ]; then
        ## on amd64 builds we need to also bundle the i386 wine loaders
        DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-i386/${WINE_REL}-i386_${WINE_VER}~bionic_i386.deb"
      fi

      for DEB_URL in ${DEB_URLS}; do
        DEB=$(basename "${DEB_URL}")
        echo "Downloading ${DEB_URL}..."
        wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
        echo "Unpacking ${DEB}..."
        dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
        rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      done

      # Organise and cleanup
      cp -a ${SNAPCRAFT_PART_INSTALL}/opt/${WINE_REL}/* ${SNAPCRAFT_PART_INSTALL}/
    stage:
      - -opt
      - -share/applications
      - -share/man
      - -usr/share/doc
      - -usr/share/lintian
    after:
      - enable-i386

  wine-runtime:
    plugin: nil
    override-build: |
      snapcraftctl build

      # Ensure the folders used in the snap layout exist
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/dri
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/gdk-pixbuf-2.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/gstreamer1.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/gstreamer-1.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/gtk-3.0
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/mesa
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/mesa-egl
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/pulseaudio
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/{i386,x86_64}-linux-gnu/samba
    stage-packages:
      ### Depends from wine-devel-${SNAP_ARCH}_3.9.0~bionic_${SNAP_ARCH}.deb debian/control
      - libasound2
      - libasound2-plugins
      - libglib2.0-0
      - libgphoto2-6
      - gstreamer1.0-plugins-base
      - libgstreamer-plugins-base1.0-0
      - liblcms2-2
      - libldap-2.4-2
      - libmpg123-0
      - libncurses5
      - libopenal1
      - libpcap0.8
      - libpulse0
      - libudev1
      - libxext6
      - libxml2
      - zlib1g
      ### Recommends from wine-devel-${SNAP_ARCH}_3.9.0~bionic_${SNAP_ARCH}.deb debian/control
      - libcups2
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libgif7
      - libglu1-mesa
      - libgnutls30
      - libgpg-error0
      - libgsm1
      - libgssapi-krb5-2
      - libjpeg8
      - libodbc1
      - libosmesa6
      - libpng16-16
      - libsane
      - libsdl2-2.0-0
      - libsqlite3-0
      - libtiff5
      - libva-drm2
      - libva-x11-2
      - libva2:i386
      - libva2
      - libv4l-0
      - libvulkan1
      - libxcomposite1
      - libxcursor1
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxxf86vm1
      - locales-all
      - va-driver-all
      # Required for authentication - Observed in Steam and Track Mania
      - samba-libs
      - winbind
      # GTK 3
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-standard
      - ibus-gtk3
      - libappindicator3-1
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libgtk-3-bin
      - libibus-1.0-5
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - light-themes
      - shared-mime-info
      - ttf-ubuntu-font-family
      - unity-gtk3-module
      - xdg-user-dirs
      # vulkan
      - mesa-vulkan-drivers
      - on amd64:
        ### Depends from wine-devel-i386_3.9.0~bionic_i386.deb debian/control
        - libasound2:i386
        - libasound2-plugins:i386
        - libc6:i386
        - libglib2.0-0:i386
        - libgphoto2-6:i386
        - gstreamer1.0-plugins-base:i386
        - libgstreamer-plugins-base1.0-0:i386
        - liblcms2-2:i386
        - libldap-2.4-2:i386
        - libmpg123-0:i386
        - libncurses5:i386
        - libopenal1:i386
        - libpcap0.8:i386
        - libpulse0:i386
        - libudev1:i386
        - libxext6:i386
        - libxml2:i386
        - zlib1g:i386
        ### Recommends from wine-devel-i386_3.9.0~bionic_i386.deb debian/control
        - libcups2:i386
        - libdbus-1-3:i386
        - libfontconfig1:i386
        - libfreetype6:i386
        - libgif7:i386
        - libglu1-mesa:i386
        - libgnutls30:i386
        - libgpg-error0:i386
        - libgsm1:i386
        - libgssapi-krb5-2:i386
        - libjpeg8:i386
        - libodbc1:i386
        - libosmesa6:i386
        - libpng16-16:i386
        - libsane:i386
        - libsdl2-2.0-0:i386
        - libsqlite3-0:i386
        - libtiff5:i386
        - libv4l-0:i386
        - libva-wayland2
        - libva-drm2:i386
        - libva-x11-2:i386
        - libva2:i386
        - libvulkan1:i386
        - libxcomposite1:i386
        - libxcursor1:i386
        - libxfixes3:i386
        - libxi6:i386
        - libxinerama1:i386
        - libxrandr2:i386
        - libxrender1:i386
        - libxslt1.1:i386
        - libxxf86vm1:i386
        - va-driver-all:i386
        # Required for authentication - Observed in Steam and Track Mania
        - samba-libs:i386
        - winbind:i386
        # GTK 3
        - ibus-gtk3:i386
        - libappindicator3-1:i386
        - libgdk-pixbuf2.0-0:i386
        - libgtk-3-0:i386
        - libgtk-3-bin:i386
        - libibus-1.0-5:i386
        - libxkbcommon0:i386  # XKB_CONFIG_ROOT
        - unity-gtk3-module:i386
        # vulkan
        - mesa-vulkan-drivers:i386
    stage:
      - -etc/init
      - -etc/init.d
      - -etc/logrotate.d
      - -usr/share/apps
      - -usr/share/applications
      - -usr/share/bug
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/debhelper
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/pixmaps
      - -usr/share/pkgconfig
    after:
      - enable-i386

  stars:
    plugin: dump
    source: scripts
    organize:
      'snap-*': bin/
      'sommelier': bin/
      'winetricks': bin/
      'zenity': bin/
    build-packages:
      - curl
    stage-packages:
      - cabextract         # winetricks
      - libgdk-pixbuf2.0-0 # yad
      - libgtk-3-0         # yad
      - libnotify4         # yad
      - libnotify-bin      # sommelier
      - perl-base          # winetricks
      - rsync
      - shared-mime-info
      - unzip              # winetricks
      - wget               # winetricks
      - yad                # winetricks
      - x11-xserver-utils  # for xrandr to set virtual desktop
    override-pull: |
      snapcraftctl pull

      curl --silent --show-error --location "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -o winetricks
      chmod +x winetricks

      curl --silent --show-error --location https://www.gog.com/galaxy | grep 'https://content-system\.gog\.com/open_link/download?path=/open/galaxy/client/setup_galaxy.*\.exe' | head -n1 | sed -E -e 's|^.*"https://content-system\.gog\.com/open_link/download\?path=/open/galaxy/client/setup_galaxy_(.*)\.exe".*$|\1|' > version
      snapcraftctl set-version "$(cat version)"
    stage:
      - -etc/init
      - -etc/init.d
      - -etc/logrotate.d
      - -usr/bin/fc-*
      - -usr/bin/gtk-*
      - -usr/lib/dconf/dconf-service
      - -usr/lib/glib-networking/glib-pacrunner
      - -usr/share/GConf
      - -usr/share/aclocal
      - -usr/share/apport
      - -usr/share/apps
      - -usr/share/bash-completion
      - -usr/share/bug
      - -usr/share/debhelper
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/icons/Adwaita
      - -usr/share/icons/Humanity*
      - -usr/share/icons/LoginIcons
      - -usr/share/icons/ubuntu-mono*
      - -usr/share/info
      - -usr/share/kde4
      - -usr/share/lintian
      - -usr/share/menu
      - -usr/share/man
      - -usr/share/perl5
      - -usr/share/pixmaps
      - -usr/share/pkgconfig
    after:
      - enable-i386
