name: stars
version: '2.7jrc3'
icon: desktop/icon.png
summary: STARS!
description: |
  Stars! is a turn-based strategy, science fiction 4X game. Stars! was developed
  by Jeff Johnson and Jeff McBride ("the Jeffs") for their own use, and
  initially released as shareware in 1995. A retail version was later produced
  for, and published by Empire Interactive, although the shareware version
  continued.

  It is no longer possible to purchase new Stars! serials, so under the
  principal of abandonware keys to unlock the game are included below.

  Keys:
    Choose one key from this list. In multiplayer mode, each player must have a
    unique serial number.
    
    Each key is eight (8) characters.

    E4TP99BW | E2BO659A | ECN101WP | EUTBD0AV | CJWLADUE | CXG6TIQX | CXLSIXTL
    CXR6TCXY | EPA8IRTP | GVZC2FZ5 | GX5RODYA | HAIDAAWS | HB5JYSQH | IFNKZG2R
    JU9VWLDF | SEOMBS8E | STDAG49L | SU0ODX1T | WBXU2GIX | WCES1YRZ | WV1EFJKF
    WV53517J | WX8Z8HLP | CJWLADUE | CXG6TIQX | CXLSIXTL | CXR6TCXY | EPA8IRTP
    GVZC2FZ5 | GX5RODYA | HAIDAAWS | HB5JYSQH | IFNKZG2R | JU9VWLDF | SEOMBS8E
    STDAG49L | SU0ODX1T | WBXU2GIX | WCES1YRZ | WV1EFJKF | WV53517J | WX8Z8HLP

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  RUN_EXE: "$SNAP/Stars-27jrc3.exe"
  TRICKS: "corefonts"
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  LC_ALL: "C.UTF-8"
  SNAP_TITLE: "$SNAPCRAFT_PROJECT_SUMMARY"
  SNAP_ICON: "$SNAP/meta/gui/icon.png"
  SNAP_SUPPORT_URL: "https://github.com/diddlesnaps/stars/issues"

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable: # number must match the number in default-provider
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable # must be a valid snap

apps:
  stars:
    extensions: [gnome-3-28]
    command: bin/sommelier run-exe
    desktop: usr/share/applications/desktop-file.desktop
    plugs:
      - desktop
      - desktop-legacy
      - home
      - network
      - removable-media
      - wayland
      - x11
  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network

parts:
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"

  desktop:
    plugin: dump
    source: desktop
    organize:
      icon.png: usr/share/icons/icon.png
      desktop-file.desktop: usr/share/applications/desktop-file.desktop

  stars:
    plugin: dump
    source: scripts
